feature/lesson_13 calculator
Nadya101/NCalculator pull request #1
Opened 2021-11-08 22:58 UTC by Nadya101

![lesson_13](https://user-images.githubusercontent.com/44065623/140831450-64172749-97aa-4076-b4e8-5004024d8d3c.png)

2021-11-11 17:00 UTC, vchesnakoutest requested changes

2021-11-11 17:00 UTC, vchesnakoutest commented on src/main/java/calc/Main.java
> +        while (exit != 0);
main класс нам в принципе не нужен, мы тестируем через TestNG

2021-11-11 17:00 UTC, vchesnakoutest commented on src/main/java/calc/Menu.java
> +    }
Scanner тоже в принципе не нужен

2021-11-11 17:00 UTC, vchesnakoutest commented on src/test/java/tests/AddTest.java
> +            Thread.sleep(1);
слипы старайся не использовать просто так

2021-11-11 17:00 UTC, vchesnakoutest commented on src/test/java/tests/ReadDoubleTest.java
> +    }
немного странный тест конечно, считывать и проверять с консоли что-то в принципе не обязательно )

2021-11-21 21:39 UTC, Nadya101 commented on src/test/java/tests/ReadDoubleTest.java
> +    }
Удалила

2021-11-21 21:43 UTC, merged